### ISSUE TITLE
Wrong type for TitleArgs in the Notification struct 

### ISSUE THREAD

**Issue by ghost** [appleboy/go-fcm#29]
How can I pass `TitleLocArgs` and `BodyLocArgs` values as array of strings? In the `message.go` file
these values are defined as plain strings whereas [FCM documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref) specifies them as array of strings .

https://github.com/appleboy/go-fcm/blob/422fb96ea5a8a58572ccc289688d0e4db35f77ac/message.go#L38
https://github.com/appleboy/go-fcm/blob/422fb96ea5a8a58572ccc289688d0e4db35f77ac/message.go#L36

**Comment by daurensr** [comment]
When I make a request with `TitleLocArgs` I get an error `Error Message: unknown error type`. However when I make same request connecting directly to FCM server everything works fine.
