### ISSUE TITLE
Critical sound

### ISSUE THREAD

**Issue by Fublvckmagik** [appleboy/go-fcm#30]
How can I set "critical" key for sound object for IOS Notifications?
```
"sound": {  
    "critical": 1,
}
```

**Comment by appleboy** [comment]
Due to [Migrate from legacy FCM APIs to HTTP v1][1]. Please see the news in the comment https://github.com/appleboy/go-fcm/issues/38#issuecomment-2121660454 

[1]:https://firebase.google.com/docs/cloud-messaging/migrate-v1
