### ISSUE TITLE
Response error is a pointer

### ISSUE THREAD

**Issue by fannar** [appleboy/go-fcm#34]
When the response has an error, the error message is a pointer.

```
2022/03/11 11:24:12 &fcm.Response{
	MulticastID:999999999999999999,
	Success:0,
	Failure:1,
	CanonicalIDs:0,
	Results:[]fcm.Result{
		fcm.Result{
			MessageID:"",
			RegistrationID:"",
			Error:(*errors.errorString)(0x14000112de0)
		}
	},
	FailedRegistrationIDs:[]string(nil),
	MessageID:0,
	Error:error(nil)
}
```

**Comment by appleboy** [comment]
Due to [Migrate from legacy FCM APIs to HTTP v1][1]. Please see the news in the comment https://github.com/appleboy/go-fcm/issues/38#issuecomment-2121660454 

[1]:https://firebase.google.com/docs/cloud-messaging/migrate-v1
