### ISSUE TITLE
Not working for iOS devices with FCM Firebase token 

### ISSUE THREAD

**Issue by alymbouras** [appleboy/go-fcm#35]
Not working for **iOS** devices with Firebase.

Gorush (https://github.com/appleboy/gorush) works fine with the same FCM token from Firebase.

**Comment by appleboy** [comment]
Due to [Migrate from legacy FCM APIs to HTTP v1][1]. Please see the news in the comment https://github.com/appleboy/go-fcm/issues/38#issuecomment-2121660454 

[1]:https://firebase.google.com/docs/cloud-messaging/migrate-v1
