### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by MirkoUgoliniDev** [appleboy/go-fcm#36]
Hello all, 

I got this error installing the library

pi@raspberrypi:~ $ go version
go version go1.17.3 linux/arm
pi@raspberrypi:~ $ go get github.com/appleboy/go-fcm
# runtime/internal/sys
/usr/local/go/src/runtime/internal/sys/stubs.go:9:7: PtrSize redeclared in this block
        /usr/local/go/src/runtime/internal/sys/arch.go:24:38: previous declaration
/usr/local/go/src/runtime/internal/sys/stubs.go:10:24: undefined: Uintreg

someone can hel p me ?

Regards

Mirko

**Comment by appleboy** [comment]
Can't reproduce.
