### ISSUE TITLE
net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by mohammadrezaataeii** [appleboy/go-fcm#37]
`message := &fcm.Message{
		To: firebaseID,
		Notification: &fcm.Notification{
			Title: "New Notification",
			Body:  contentMessage,
		},
	}

	response, err := fcmClient.Send(message)
	if err != nil {
		return err
	}`
when this part has been run after seconds this error returned :
net/http: TLS handshake timeout
what is propblem ?

**Comment by appleboy** [comment]
Due to [Migrate from legacy FCM APIs to HTTP v1][1]. Please see the news in the comment https://github.com/appleboy/go-fcm/issues/38#issuecomment-2121660454 

[1]:https://firebase.google.com/docs/cloud-messaging/migrate-v1
