### ISSUE TITLE
FCM deprecated HTTP legacy send API

### ISSUE THREAD

**Issue by netrebel** [appleboy/go-fcm#38]
On 6/27/2023, we started getting `Post \"https://fcm.googleapis.com/fcm/send\": context deadline exceeded` errors (less than 0.2% of the total) in our service that sends push-notifications to FCM.

Looking at FCM announcements, I found that the current API will be discontinued in June 2024 (I'm not sure this is related the announcement):

> Firebase has announced that it will discontinue legacy Firebase Cloud Messaging (FCM) APIs starting from June 20, 2024. This decision comes as part of Firebase’s efforts to enhance security and performance. As a result, certain APIs will be deprecated in favor of the available alternatives.

https://blogiestools.com/firebase-legacy-fcm-apis-discontinued/

They have already started deprecating the API, the HTTP legacy APIs was deprecated on **June 20, 2023**:

> Caution: Sending messages (including upstream messages) with the FCM XMPP and HTTP legacy APIs was deprecated on June 20, 2023, and will be removed in June 2024. If you are using the legacy send APIs, we strongly recommend that you [migrate to the HTTP v1 API](https://firebase.google.com/docs/cloud-messaging/migrate-v1) or consider using the [Admin SDK](https://firebase.google.com/docs/cloud-messaging/server#choosing-a-server-option) to build send requests.

# Migration instructions

See the migration instructions here: https://firebase.google.com/docs/cloud-messaging/migrate-v1 

HTTP requests before: 

```
POST https://fcm.googleapis.com/fcm/send
```

After:

```
POST https://fcm.googleapis.com/v1/projects/myproject-b5ae1/messages:send
```

[appleboy/go-fcm/client.go](https://github.com/life360/push360/blob/4949bdacafadfa3ed775a673494c0aa04a814178/vendor/github.com/appleboy/go-fcm/client.go#L15) uses:

```
DefaultEndpoint = "https://fcm.googleapis.com/fcm/send"
```

Are there plans to update this Endpoint in the library?

**Comment by pvincendeau** [comment]
+ 1

**Comment by petenickless** [comment]
+1

**Comment by RakiFuyumine** [comment]
+ 1

**Comment by dm-aq** [comment]
+1

**Comment by esg42** [comment]
+1

**Comment by appleboy** [comment]
I will take it.

**Comment by huangyuhui-github** [comment]
Hi，when do you fixed this issue ? Do you have any plan ?

**Comment by netrebel** [comment]
Same question as last post. Would be good to know an ETA to consider waiting for the new version or completely switching implementation. This library has been working great so far sending push-notifications to FCM! Thanks for all the work. 🙏

**Comment by netrebel** [comment]
Found out that the library provided by Google calls the new endpoint: `v1/projects/{projectsId}/messages:send`:
https://github.com/googleapis/google-api-go-client/blob/main/fcm/v1/fcm-api.json#L117

Will look into that as the alternative to this library.

**Comment by vasteez** [comment]
+1 to this. Any info on ETA?

**Comment by appleboy** [comment]
We should move to https://firebase.google.com/docs/cloud-messaging/server SDK.

**Comment by vasteez** [comment]
> Maybe we should move to https://firebase.google.com/docs/cloud-messaging/server SDK.

@appleboy On January 30 you said you'd take this on.

Wondering if you found out any information?

1. Will the `go-fcm` library easily port to the new API, or do we need a major refactor?
2. What do you mean with moving to the cloud-messaging SDK. Does that mean updating this `go-fcm` with that SDK or completely moving off of `go-fcm`
3. I guess i'm more of just wondering what the state of `go-fcm` as it's Google API will be removed [next month ](https://firebase.google.com/docs/cloud-messaging/migrate-v1).

Thanks for your time @appleboy, we've used this library for a while now

**Comment by netrebel** [comment]
> Maybe we should move to https://firebase.google.com/docs/cloud-messaging/server SDK.

Same question, would **Firebase Admin SDK** (https://pkg.go.dev/firebase.google.com/go/v4/messaging) replace `go-fcm` or be used inside `go-fcm`?

**Comment by appleboy** [comment]
@netrebel @vasteez 

I will integrate the go-fcm package with the Firebase SDK for the next version improvement. Therefore, everyone can still use this package.

**Comment by netrebel** [comment]
> @netrebel @vasteez
> 
> I will integrate the go-fcm package with the Firebase SDK for the next version improvement. Therefore, everyone can still use this package.

That's great news! thanks for the update. Is there a target date to have the new version of the library @appleboy ?

**Comment by vasteez** [comment]
@appleboy 

The FCM [documentation](https://firebase.google.com/docs/cloud-messaging/migrate-v1) mentions these legacy APIs will be removed in June 2024 (15 days from now)

Do you have an idea of the scope of changes that'll take to update this library and how long it'd take?

**Comment by gyndav** [comment]
@vasteez precisely the following `We’re writing to remind you that starting June 20, 2024 the legacy Firebase Cloud Messaging (FCM) APIs will be discontinued.`

**Comment by appleboy** [comment]
Hi All,

I have completed the initial development, and everyone can test it using the following method. Please refer to the readme for instructions on how to use it.

```go
package main

import (
  "context"
  "fmt"
  "log"

  "firebase.google.com/go/v4/messaging"
  fcm "github.com/appleboy/go-fcm"
)

func main() {
  client, err := fcm.NewClient(
    context.Background(),
    fcm.WithCredentialsFile("path/to/serviceAccountKey.json"),
  )
  if err != nil {
    log.Fatal(err)
  }

  // Send to a single device
  token := "test"
  resp, err := client.Send(
    context.Background(),
    &messaging.Message{
      Token: token,
      Data: map[string]string{
        "foo": "bar",
      },
    },
  )
  if err != nil {
    log.Fatal(err)
  }

  fmt.Println("success count:", resp.SuccessCount)
  fmt.Println("failure count:", resp.FailureCount)
  fmt.Println("message id:", resp.Responses[0].MessageID)
  fmt.Println("error msg:", resp.Responses[0].Error)
}
```

**Comment by vasteez** [comment]
@appleboy thanks for the quick update!

Few questions. It looks like we used to authenticate with an apiKey but now you get it from `path/to/serviceAccountKey.json`

1. Is there a way to continue using apiKey as we used to?
2. If not, where do we get this serviceAccountKey.json file? I tried generating that file in the Firebase Service Accounts dashboard but it did not have the key in it which is expected in `client.go` [here](https://github.com/appleboy/go-fcm/blob/master/client.go)
3. In the above linked file (`client.go`) the key `serviceAcount` is mispelled, leading me to believe this `.json` file is not some google generated json

**Comment by netrebel** [comment]
> @appleboy thanks for the quick update!
> 
> Few questions. It looks like we used to authenticate with an apiKey but now you get it from `path/to/serviceAccountKey.json`
> 
> 1. Is there a way to continue using apiKey as we used to?

No, the new way uses oauth2 tokens.

> 2. If not, where do we get this serviceAccountKey.json file? I tried generating that file in the Firebase Service Accounts dashboard but it did not have the key in it which is expected in `client.go` [here](https://github.com/appleboy/go-fcm/blob/master/client.go)

I used parts of this guide to generate the file. See from Step 3
https://www.braze.com/docs/en/developer_guide/platform_integration_guides/android/push_notifications/android/migrating_to_firebase_cloud_messaging/

Summary:
1. Create Service Account (add _Firebase Cloud Messaging API_ permissions)
2. Go to [Service Accounts](https://console.cloud.google.com/iam-admin/serviceaccounts). Select your newly created SA, click on Keys, then "Add Key". That will create the key and give you the JSON file you need.

**Comment by appleboy** [comment]
I updated the readme. https://github.com/appleboy/go-fcm#provide-credentials-using-adc To generate a private key file for your service account.

**Comment by netrebel** [comment]
@appleboy, tried out the latest version already, it worked perfectly! 💯 

One question, we used to overwrite `Timeout` and `Transport` with a custom `httpClient`.  E.g:

```go
httpTimeout := time.Duration(5) * time.Second
tlsTimeout := time.Duration(5) * time.Second

transport := &http2.Transport{
	DialTLS: func(network, addr string, cfg *tls.Config) (net.Conn, error) {
		return tls.DialWithDialer(&net.Dialer{Timeout: tlsTimeout}, network, addr, cfg)
	},
}

httpClient := &http.Client{
	Transport: transport,
	Timeout:   httpTimeout,
}

client, err := fcm.NewClient(
	context.Background(),
	fcm.WithCredentialsFile("life360.com_safetymapqa-4b811818a846.json"),
	fcm.WithHTTPClient(httpClient),
)
```

But if I do that, I get this error when trying to `send`:
```
Request is missing required authentication credential. 
Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```

But without that line `fcm.WithHTTPClient(httpClient)`, the client works fine ✅ . 

Question: Is there a way to still do this? I see that there's `WithCustomClientOption` but not sure how to use this.

p.s. I think this was an effort reduce the `Timeouts` we get from FCM, but those lines of code have been there for many years! Maybe this is not needed anymore, but thought I'd ask anyways.

Thanks!

**Comment by appleboy** [comment]
@netrebel Thanks for your report. I will take it.

**Comment by appleboy** [comment]
@netrebel Quick update:

1. Support custom HTTP Clients now.
2. Remove confuse function: `WithCustomClientOption`

## custom HTTP client

```go
func main() {
	httpTimeout := time.Duration(5) * time.Second
	tlsTimeout := time.Duration(5) * time.Second

	transport := &http2.Transport{
		DialTLS: func(network, addr string, cfg *tls.Config) (net.Conn, error) {
			return tls.DialWithDialer(&net.Dialer{Timeout: tlsTimeout}, network, addr, cfg)
		},
	}

	httpClient := &http.Client{
		Transport: transport,
		Timeout:   httpTimeout,
	}

	ctx := context.Background()
	client, err := fcm.NewClient(
		ctx,
		fcm.WithCredentialsFile("fcm-demo-88b40-firebase-adminsdk-6ezlh-adb6c96ab1.json"),
		fcm.WithHTTPClient(httpClient),
	)
	if err != nil {
		log.Fatal(err)
	}

	// Send to a single device
	token := "test"
	resp, err := client.Send(
		ctx,
		&messaging.Message{
			Token: token,
			Data: map[string]string{
				"foo": "bar",
			},
		},
	)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("success count:", resp.SuccessCount)
	fmt.Println("failure count:", resp.FailureCount)
	fmt.Println("message id:", resp.Responses[0].MessageID)
	fmt.Println("error msg:", resp.Responses[0].Error)
}
```

## Support proxy URL

```go
func main() {
	ctx := context.Background()
	client, err := fcm.NewClient(
		ctx,
		fcm.WithCredentialsFile("fcm-demo-88b40-firebase-adminsdk-6ezlh-adb6c96ab1.json"),
		fcm.WithHTTPProxy("http://localhost:8088"),
	)
	if err != nil {
		log.Fatal(err)
	}

	// Send to a single device
	token := "test"
	resp, err := client.Send(
		ctx,
		&messaging.Message{
			Token: token,
			Data: map[string]string{
				"foo": "bar",
			},
		},
	)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("success count:", resp.SuccessCount)
	fmt.Println("failure count:", resp.FailureCount)
	fmt.Println("message id:", resp.Responses[0].MessageID)
	fmt.Println("error msg:", resp.Responses[0].Error)
}
```

**Comment by appleboy** [comment]
I created new tag v1.0.0 https://github.com/appleboy/go-fcm/releases/tag/v1.0.0

**Comment by vasteez** [comment]
Unfortunately this solution wont work for us as the new library upgrades a bunch of dependencies that we cannot quickly update.

But thanks regardless @appleboy -- i'm sure i'll be referencing your solution in whatever we build

**Comment by vasteez** [comment]
Was able to resolve my issues by forking your library and changing some go modules.

Thank you @appleboy for getting this working really appreciate it! 🙏

**Comment by appleboy** [comment]
@vasteez Can you send the new PR? We should collaboratively maintain a repository.

**Comment by vasteez** [comment]
@appleboy When I try to push to a new branch to open a PR I get a permission error

![image](https://github.com/appleboy/go-fcm/assets/61713900/8cadcbfc-8585-4a92-b412-5bacb61bb744)

But regardless -- I don't think this is a change you want merged. My only diff is deleting all the `requires` in go.mod 

![image](https://github.com/appleboy/go-fcm/assets/61713900/cdb9b99e-158e-4ef6-96f2-9b176adc0d40)

Reason being your go.mod depended on us upgrading a bunch of dependencies we could not in reasonable time, so getting rid of those requires resolved it. The functionality still works fine for us, but might not for other on different versions.
