### ISSUE TITLE
getting error on dependency.

### ISSUE THREAD

**Issue by bhaveshitankar** [appleboy/go-fcm#55]
google.golang.org/grpc/credentials/insecure: module google.golang.org/grpc@latest found (v0.0.0-00010101000000-000000000000, replaced by google.golang.org/grpc@v1.27.0), but does not contain package google.golang.org/grpc/credentials/insecure

**Comment by appleboy** [comment]
try https://github.com/appleboy/go-fcm/releases/tag/v1.2.1
