### ISSUE TITLE
Query : is the token generated by this library short live or it will auto refresh.

### ISSUE THREAD

**Issue by bhaveshitankar** [appleboy/go-fcm#59]

**Comment by appleboy** [comment]
You can see the reference: https://firebase.google.com/docs/cloud-messaging/manage-tokens#stale-and-expired-tokens

## Stale and expired registration tokens

Stale registration tokens are tokens associated with inactive devices that have not connected to FCM for over a month. As time passes, it becomes less and less likely for the device to ever connect to FCM again. Message sends and topic fanouts for these stale tokens are unlikely to ever be delivered.

There are several reasons why a token can become stale. For example, the device the token is associated with may be lost, destroyed, or put into storage and forgotten.

When stale tokens reach 270 days of inactivity, FCM will consider them expired tokens. Once a token expires, FCM marks it as invalid and rejects sends to it. However, FCM issues a new token for the app instance in the rare case that the device connects again and the app is opened.
